-- Add Unique Lessons for Each Course
-- This will create distinct lessons for all 3 courses

-- =====================================================
-- BEGINNER ENGLISH COURSE LESSONS
-- =====================================================

-- Module 1: Grammar Foundations
INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES
('lesson_grammar_basics_1', 'module_basics_grammar', 'Parts of Speech Introduction', 'Learn about nouns, verbs, adjectives with AI examples', 1, 'lecture', 'Welcome to Grammar Basics! Today we will learn about the fundamental building blocks of English grammar: Parts of Speech.\n\nWhat are Parts of Speech?\nParts of speech are categories of words based on their function in a sentence.\n\nThe 8 Main Parts of Speech:\n1. NOUNS - names of people, places, things (cat, London, happiness)\n2. VERBS - action or state words (run, is, think)\n3. ADJECTIVES - describe nouns (beautiful, big, happy)\n4. ADVERBS - describe verbs (quickly, very, always)\n5. PRONOUNS - replace nouns (he, she, it, they)\n6. PREPOSITIONS - show relationships (in, on, at, to)\n7. CONJUNCTIONS - connect words (and, but, or)\n8. INTERJECTIONS - express emotion (wow, ouch, hello)\n\nPractice Examples:\n- "The QUICK brown fox JUMPS over the LAZY dog"\n  Quick = adjective, brown = adjective, fox = noun, jumps = verb, lazy = adjective, dog = noun\n\nRemember: Understanding parts of speech helps you build correct sentences!', 'easy', 20, '["Identify 8 main parts of speech", "Understand the role of each part", "Apply knowledge in simple sentences"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES
('lesson_grammar_basics_2', 'module_basics_grammar', 'Present Simple Tense', 'Master the present simple for habits and facts', 2, 'lecture', 'The Present Simple Tense\n\nWhen do we use Present Simple?\n1. For habits and routines\n   - I wake up at 7 AM every day.\n   - She drinks coffee in the morning.\n\n2. For permanent situations\n   - They live in New York.\n   - He works as a teacher.\n\n3. For general truths\n   - The sun rises in the east.\n   - Water boils at 100°C.\n\nFormation:\nPositive: Subject + base verb (+ s/es for he/she/it)\n- I work, You work, He/She works, We work, They work\n\nNegative: Subject + do/does + not + base verb\n- I don''t work, He doesn''t work\n\nQuestion: Do/Does + subject + base verb?\n- Do you work? Does she work?\n\nCommon Mistakes:\n❌ He work (WRONG)\n✅ He works (CORRECT)\n\n❌ She don''t like (WRONG)\n✅ She doesn''t like (CORRECT)\n\nPractice: Try making 5 sentences about your daily routine!', 'easy', 25, '["Form present simple correctly", "Use with I/you/we/they and he/she/it", "Create habit sentences"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES
('lesson_grammar_basics_3', 'module_basics_grammar', 'Past Simple Tense', 'Learn to talk about completed past actions', 3, 'lecture', 'The Past Simple Tense\n\nUse Past Simple for:\n- Completed actions in the past\n- Specific time in the past\n\nRegular Verbs (+ ed):\n- work → worked\n- play → played\n- study → studied\n\nIrregular Verbs (memorize these!):\n- go → went\n- eat → ate\n- see → saw\n- have → had\n- make → made\n\nFormation:\nPositive: Subject + past form\n- I worked yesterday\n- She went to school\n\nNegative: Subject + did not + base verb\n- I didn''t work yesterday\n- She didn''t go to school\n\nQuestion: Did + subject + base verb?\n- Did you work yesterday?\n- Did she go to school?\n\nTime Expressions:\n- yesterday, last week, last year\n- in 2020, two days ago\n- when I was young\n\nExample Story:\n"Yesterday, I woke up late. I didn''t have breakfast. I went to work by bus. At lunch, I ate a sandwich. In the evening, I watched TV and went to bed at 10 PM."\n\nYour turn: Write about what you did yesterday!', 'medium', 30, '["Use regular and irregular past forms", "Form past simple questions", "Tell stories about past events"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Module 2: Essential Vocabulary
INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES
('lesson_vocab_basics_1', 'module_basics_vocabulary', 'Daily Routine Vocabulary', 'Essential words for everyday activities', 1, 'lecture', 'Daily Routine Vocabulary\n\nMorning Activities:\n- wake up (stop sleeping)\n- get up (leave bed)\n- brush my teeth\n- take a shower\n- have breakfast\n- get dressed\n- leave home\n- go to work/school\n\nAfternoon:\n- have lunch\n- work/study\n- take a break\n- finish work\n- go home\n\nEvening:\n- have dinner\n- relax\n- watch TV\n- do homework\n- go to bed\n- fall asleep\n\nUseful Phrases:\n"I usually wake up at 7 AM."\n"I have breakfast before going to work."\n"In the evening, I relax with my family."\n\nTime Expressions:\n- in the morning/afternoon/evening\n- at night\n- before/after work\n- on weekdays/weekends\n\nPractice: Describe your typical day using these words!', 'easy', 20, '["Use 20+ daily routine verbs", "Describe your schedule", "Use time expressions correctly"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- =====================================================
-- BUSINESS ENGLISH COURSE LESSONS
-- =====================================================

-- Module 1: Professional Email Writing
INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES
('lesson_business_email_1', 'module_business_emails', 'Email Structure and Greetings', 'Professional email format and opening lines', 1, 'lecture', 'Professional Email Structure\n\nStandard Business Email Format:\n\n1. SUBJECT LINE\n- Clear and specific\n- Professional tone\n- Action-oriented\n\nExamples:\n✅ "Meeting Request - Project Update"\n✅ "Follow-up: Marketing Proposal"\n❌ "Hi" or "Question" (too vague)\n\n2. GREETING\nFormal:\n- Dear Mr./Ms. [Last Name],\n- Dear Sir/Madam, (when name unknown)\n\nSemi-formal:\n- Dear [First Name],\n- Hello [Name],\n\nInformal (colleagues):\n- Hi [Name],\n- Hey [Name],\n\n3. OPENING LINE\nFirst email:\n- "I hope this email finds you well."\n- "Thank you for your inquiry about..."\n- "I am writing to..."\n\nFollow-up:\n- "Following up on our conversation..."\n- "As discussed in our meeting..."\n- "Further to my previous email..."\n\n4. BODY\n- Be clear and concise\n- Use paragraphs\n- Bullet points for lists\n- Professional tone\n\n5. CLOSING\n- "Best regards,"\n- "Kind regards,"\n- "Sincerely," (very formal)\n- "Thank you," (when requesting)\n\n6. SIGNATURE\n- Full name\n- Job title\n- Company\n- Contact info\n\nExample Email:\n"Dear Ms. Johnson,\n\nI hope this email finds you well. I am writing to request a meeting to discuss the upcoming product launch.\n\nWould you be available next Tuesday at 2 PM? Please let me know if this time works for you.\n\nBest regards,\nJohn Smith\nMarketing Manager\nABC Company"\n\nRemember: Professional = Clear + Polite + Concise', 'medium', 25, '["Structure professional emails correctly", "Choose appropriate greetings", "Write clear opening lines"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES  
('lesson_business_email_2', 'module_business_emails', 'Making Requests and Responses', 'Professional ways to ask and answer', 2, 'lecture', 'Making Professional Requests\n\nPolite Request Structures:\n\n1. ASKING FOR INFORMATION\n- "Could you please provide...?"\n- "I would appreciate if you could..."\n- "Would it be possible to...?"\n- "I was wondering if you could..."\n\n2. MAKING REQUESTS\nDirect (less formal):\n- "Please send me..."\n- "Can you help me with...?"\n\nIndirect (more polite):\n- "Would you mind sending...?"\n- "I would be grateful if you could..."\n- "Could you kindly...?"\n\n3. SETTING DEADLINES\n- "Please send this by Friday."\n- "I would need this by end of day."\n- "Could you have this ready by tomorrow?"\n\n4. RESPONDING TO REQUESTS\nAgreeing:\n- "Of course, I''d be happy to help."\n- "Yes, I can send that today."\n- "No problem at all."\n\nNegative (polite):\n- "Unfortunately, I won''t be able to..."\n- "I''m afraid that won''t be possible because..."\n- "I apologize, but I cannot..."\n\nOffering alternatives:\n- "However, I could..."\n- "Would [alternative] work instead?"\n- "Let me suggest..."\n\n5. FOLLOWING UP\n- "I wanted to follow up on my previous email..."\n- "Just checking if you had a chance to..."\n- "Following our conversation..."\n\nExample Request:\n"Dear Team,\n\nI would appreciate if you could review the attached document and provide your feedback by Thursday. Please let me know if you have any questions.\n\nThank you for your cooperation.\n\nBest regards,"\n\nPractice: Write a polite request email for a meeting!', 'medium', 30, '["Make polite professional requests", "Respond to requests appropriately", "Use formal email language"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Add sample lessons for IELTS course as well
INSERT INTO lessons (id, module_id, title, description, order_index, lesson_type, content_text, difficulty_level, estimated_minutes, learning_objectives) VALUES
('lesson_sample_advanced', 'module_basics_grammar', 'Advanced Grammar Concepts', 'Complex sentence structures for IELTS', 1, 'lecture', 'This is a sample advanced lesson. More content will be generated by AI based on your learning needs.', 'hard', 30, '["Master complex sentences", "Use advanced grammar", "Achieve IELTS band 7+"]')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;
